### ISSUE TITLE
Jobs board?

### ISSUE THREAD

**Issue by SamRPJRoss** [ResponseDiversityNetwork/RDN-website#14]
Laura's email to advertise a postdoc position made me wonder if we might want to add a jobs board to the website, where members of the network can advertise open positions, fellowship opportunities, etc. 

If you think such a thing is useful, we can add to the newsletter for people to contact us with jobs they want to advertise. 

How does that sound?

**Comment by opetchey** [comment]
I think this might be a small win-significant cost opportunity. Small win because there are many other fora for job advertisement where people are already posting and looking... while one focused on RD would have some uniqueness, I'm not sure how we get much traffic. The cost of maintaining an up to date jobs board is not small...

**Comment by SamRPJRoss** [comment]
Thanks Owen, I was also wondering about how to maintain it. Excellent points, best to leave this one I think. 

Thanks! 
Sam
